In [1]:
#numPy

In [3]:
#install numPy library

!pip install numPy

In [6]:
#importing numpy library

import numpy as np

In [7]:
#creating arry using .array() method

arr= np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [8]:
type(arr)

numpy.ndarray

In [9]:
#to get the dimension

arr.shape

(4,)

In [10]:
#to get the data type

arr.dtype

dtype('int32')

In [13]:
# to creat 2D array

a= np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a.shape

(3, 3)

In [15]:
#we have a list

lst1=[i for i in range(10)]
lst1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
#add 2 for each number
#normal ways

lst2=[]
for i in lst1:
    lst2.append(i+2)
print(lst2)    

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [17]:
# in list comprehnsion

lst2=[i+2 for i in lst1]
print(lst2)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [18]:
# in numpy

#arange()  is similar to range()

lst_arr1=np.arange(10)
lst_arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#to add 2 to each number

lst_arr2=lst_arr1+2
lst_arr2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
#performanc measurement
#cube of all the number from 0 to 9999

%timeit [i**3 for i in range(10000)]

4.57 ms ± 468 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [22]:
#in numpy

%timeit np.arange(10000)**3

42.4 µs ± 3.73 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [23]:
#creating numPy list
#np.arange(start,stop,step)

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
np.arange(15,0,-1)

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [26]:
np.arange(15,0,-2)

array([15, 13, 11,  9,  7,  5,  3,  1])

In [1]:
# np.zeros(shape)

np.shape(3,3)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [5]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.zeros((3,3), dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
#np.zeros_like(ndarry)

In [12]:
a=np.array([[2,3],[3,4],[5,6]])
print(a)

[[2 3]
 [3 4]
 [5 6]]


In [13]:
a.shape

(3, 2)

In [14]:
np.zeros_like(a)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [15]:
np.ones_like(a)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [16]:
a=np.array([[2,3],[2,4],[8,9]])
print(a)
print(a.shape)

[[2 3]
 [2 4]
 [8 9]]
(3, 2)


In [17]:
np.ones_like(a)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [3]:
import numpy as np

In [4]:
np.diag(np.arange(1,5,0.5))

array([[1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 1.5, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 2. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 2.5, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 3. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 3.5, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 4. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 4.5]])

In [5]:
a=np.array([2,3,4,5,6,7,8,9])
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a[1]

3

In [7]:
a[5]

7

In [8]:
a[-1]

9

In [14]:
a[[0,2,4]]

array([2, 4, 6])

In [18]:
a[[1,3,6]]

array([3, 5, 8])

In [19]:
a[2:]

array([4, 5, 6, 7, 8, 9])

In [5]:
b=np.array([[1,2,3,4],[5,6,7,8],[8,9,10,11],[12,13,14,15]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
b[2,2]

10

In [7]:
b[1,2]

7

In [8]:
b[2:4,0:]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
b[2:,2:]

array([[10, 11],
       [14, 15]])

In [3]:
import numpy as np